spring:
  application: 
    name: zuul-gateway
zuul:
  routes:
    account-service:
      url: http://localhost:8080
    
    loan-service:
      url: http://localhost:8081
      
ribbon:  eureka:    enabled: false


server:  port: 8083      